// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDngl_VWDtJZu1_FxPbyjzA_tSWJbyyzrE',
    appId: '1:623073329783:web:992023494f50c73740bc72',
    messagingSenderId: '623073329783',
    projectId: 'fetching-data-api-1844d',
    authDomain: 'fetching-data-api-1844d.firebaseapp.com',
    storageBucket: 'fetching-data-api-1844d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrSTM_ctZnScYA9xGqoRFtOeI0O_qRuKQ',
    appId: '1:623073329783:android:6b25c1207674b42f40bc72',
    messagingSenderId: '623073329783',
    projectId: 'fetching-data-api-1844d',
    storageBucket: 'fetching-data-api-1844d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0TTO5IrYOwvHJfq1yYA4d5YCfyIm5AUk',
    appId: '1:623073329783:ios:4e1eef716795819140bc72',
    messagingSenderId: '623073329783',
    projectId: 'fetching-data-api-1844d',
    storageBucket: 'fetching-data-api-1844d.appspot.com',
    iosBundleId: 'com.example.fatchingDataApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDngl_VWDtJZu1_FxPbyjzA_tSWJbyyzrE',
    appId: '1:623073329783:web:89aba6d9213d30d940bc72',
    messagingSenderId: '623073329783',
    projectId: 'fetching-data-api-1844d',
    authDomain: 'fetching-data-api-1844d.firebaseapp.com',
    storageBucket: 'fetching-data-api-1844d.appspot.com',
  );
}
